### ISSUE TITLE
Document Update Conflict

### ISSUE THREAD

**Issue by ilfrich** [cloudant/meteor-couchdb#12]
I'm getting the following error message on server startup. I'm properly connected and can read/write documents. This I believe is related to the Meteor view that is somehow created.

The error only happens if I have `johdirr:meteor-git-rev` installed (a package that has nothing to do with the database).

*Cloudant credentials and instance ID are masked.*

```
W20150930-11:24:55.173(10)? (STDERR) Error: getaddrinfo ENOTFOUND
W20150930-11:24:55.175(10)? (STDERR)     at Object.Future.wait (/Users/peter/.meteor/packages/meteor-tool/.1.1.9.20ekvo++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
W20150930-11:24:55.177(10)? (STDERR)     at new CouchDBConnection (packages/cloudant_couchdb/couchdb_driver.js:141:1)
W20150930-11:24:55.205(10)? (STDERR)     at new CouchDBInternals.RemoteCollectionDriver (packages/cloudant_couchdb/remote_collection_driver.js:29:1)
W20150930-11:24:55.210(10)? (STDERR)     at Object.<anonymous> (packages/cloudant_couchdb/remote_collection_driver.js:77:1)
W20150930-11:24:55.212(10)? (STDERR)     at Object.defaultRemoteCollectionDriver (packages/underscore/packages/underscore.js:779:1)
W20150930-11:24:55.213(10)? (STDERR)     at new CouchDB.Database (packages/cloudant_couchdb/collection.js:112:1)
W20150930-11:24:55.213(10)? (STDERR)     at packages/johdirr_meteor-git-rev/packages/johdirr_meteor-git-rev.js:9:1
W20150930-11:24:55.213(10)? (STDERR)     at Package (packages/johdirr_meteor-git-rev/packages/johdirr_meteor-git-rev.js:14:1)
W20150930-11:24:55.214(10)? (STDERR)     at /Users/peter/projects/bendigo-demo/.meteor/local/build/programs/server/packages/johdirr_meteor-git-rev.js:81:4
W20150930-11:24:55.215(10)? (STDERR)     at /Users/peter/projects/bendigo-demo/.meteor/local/build/programs/server/packages/johdirr_meteor-git-rev.js:88:3
W20150930-11:24:55.215(10)? (STDERR)     - - - - -
W20150930-11:24:55.215(10)? (STDERR)     at errnoException (dns.js:37:11)
W20150930-11:24:55.215(10)? (STDERR)     at Object.onanswer [as oncomplete] (dns.js:124:16)
=> Meteor server restarted                    
W20150930-11:25:26.239(10)? (STDERR) { [Error: Document update conflict.]
W20150930-11:25:26.239(10)? (STDERR)   name: 'Error',
W20150930-11:25:26.239(10)? (STDERR)   error: 'conflict',
W20150930-11:25:26.239(10)? (STDERR)   reason: 'Document update conflict.',
W20150930-11:25:26.239(10)? (STDERR)   scope: 'couch',
W20150930-11:25:26.239(10)? (STDERR)   statusCode: 409,
W20150930-11:25:26.239(10)? (STDERR)   request: 
W20150930-11:25:26.240(10)? (STDERR)    { method: 'PUT',
W20150930-11:25:26.240(10)? (STDERR)      headers: 
W20150930-11:25:26.240(10)? (STDERR)       { 'content-type': 'application/json',
W20150930-11:25:26.240(10)? (STDERR)         accept: 'application/json' },
W20150930-11:25:26.240(10)? (STDERR)      uri: 'https://username:password@instance-bluemix.cloudant.com/revision/_design/meteor/_update/lastwritewins/S5REqHRHgCbYBjfMn',
W20150930-11:25:26.240(10)? (STDERR)      body: '{"_id":"S5REqHRHgCbYBjfMn"}' },
W20150930-11:25:26.240(10)? (STDERR)   headers: 
W20150930-11:25:26.240(10)? (STDERR)    { 'x-couch-request-id': 'c8a9b87a6b',
W20150930-11:25:26.240(10)? (STDERR)      date: 'Wed, 30 Sep 2015 01:25:17 GMT',
W20150930-11:25:26.240(10)? (STDERR)      'content-type': 'application/json',
W20150930-11:25:26.240(10)? (STDERR)      'cache-control': 'must-revalidate',
W20150930-11:25:26.240(10)? (STDERR)      'strict-transport-security': 'max-age=31536000',
W20150930-11:25:26.240(10)? (STDERR)      'x-content-type-options': 'nosniff;',
W20150930-11:25:26.240(10)? (STDERR)      statusCode: 409,
W20150930-11:25:26.241(10)? (STDERR)      uri: 'https://username:password@instance-bluemix.cloudant.com/revision/_design/meteor/_update/lastwritewins/S5REqHRHgCbYBjfMn' },
W20150930-11:25:26.241(10)? (STDERR)   errid: 'non_200',
W20150930-11:25:26.241(10)? (STDERR)   description: 'couch returned 409' }```

**Comment by mariobriggs** [comment]
In the document conflict exception, this stands out
``` 
body: '{"_id":"S5REqHRHgCbYBjfMn"}' },
``` 

that should  be the whole document (to replace doc with _id S5REqHRHgCbYBjfMn). However it contains only the _id

**Comment by ilfrich** [comment]
I investigated the issue a bit further. Turns out the package `johdirr:meteor-git-rev` is actually using MongoDB:

`Revision = new Meteor.Collection('revision');`
and
`Revision.update(revId, { $set: modifier }, function(err) {
    if (err) return console.error(err);
  });`

This is causing the issue.
